apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-oovn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-oovn
    app.kubernetes.io/part-of: hacbs-demo-test-app-iucy
  name: test-component-oovn
  namespace: hacbs-e2e-xwjk
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: test-component-oovn
    weight: 100
status: {}
